/* tslint:disable */
/* eslint-disable */
/**
 * openapi template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealthAuthResponse
 */
export interface GetHealthAuthResponse {
    /**
     * Auth status.
     * @type {string}
     * @memberof GetHealthAuthResponse
     */
    status: string;
}

/**
 * Check if a given object implements the GetHealthAuthResponse interface.
 */
export function instanceOfGetHealthAuthResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GetHealthAuthResponseFromJSON(json: any): GetHealthAuthResponse {
    return GetHealthAuthResponseFromJSONTyped(json, false);
}

export function GetHealthAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealthAuthResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function GetHealthAuthResponseToJSON(value?: GetHealthAuthResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

